spring.application.name=pacientes
server.port=8085


spring.datasource.url=jdbc:postgresql://ep-jolly-tree-ap9j4ogd-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_QVdUFu10esnW
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true